### ISSUE TITLE
Returns dramatically wrong results (from Formatting.jl)

### ISSUE THREAD

**Issue by goerz** [JuliaString/Format.jl#63]
It seems that this port is bringing over the following rather serious correctness bug from `Formatting.jl`:

https://github.com/JuliaIO/Formatting.jl/issues/108

```
julia> using Format
julia> fspec = FormatSpec(".1e")
julia> printfmt(fspec, 0.0003)
2.10e-04
```

**Comment by jariji** [comment]
Any chance this could be addressed?

**Comment by ScottPJones** [comment]
Yes - I intend to do a full rewrite of some of the formatting code (which currently has 3 different formatting paths!), to be based on the code that is already based on Ryu, which will address this issue.
