### ISSUE TITLE
Hope to have f-string like in python

### ISSUE THREAD

**Issue by zsz00** [JuliaString/Format.jl#67]
Hope to have f-string like in python

reference:
https://peps.python.org/pep-0498/
https://realpython.com/python-f-strings/
https://github.com/bicycle1885/Fmt.jl

small example:
```
a="world"
println(f"hello {a}")    # hello world

b=1.234567
c = f"number {b:.3f}"    # "number 1.235"

d="aaaa"
println(f"{d=}")   # d="aaaa", debug feature

```

Most important of all f-string enables a compact and expressive syntax which is clean, fast and fun to type.

**Comment by ScottPJones** [comment]
There already is such a thing - although not with exactly the same format (for various reasons):
Check out [StrFormat.jl](https://github.com/JuliaString/StrFormat.jl) (which uses Format.jl):

```julia
julia> using StrFormat

julia> b=1.234567
1.234567

julia> f"number \{.3f}(b)"
"number 1.235"
```

It has a number of extensions over Python f-strings, you can also do more C style formatting, or formatting based on type-specific defaults (which you can add types to, or change the formatting)

C-style:
```julia
julia> f"number \%.3f(pi)"
"number 3.142"
```

Settable defaults, with keywords:
```julia
julia> f"\%(pi*10000,20,:commas,:left)"
"31,415.926536       "
```

This is what I've used for debugging for the past 8 years 😁

**Comment by ScottPJones** [comment]
@aplavin Are you planning on supporting the rest of the Python formatting functionality, such as ^ (center justification), _ and , for group separators, # for alternate output format?
Also, there is a bug in Printf, when padding strings that have wide characters that have been truncated by the precision, that needs to get fixed in Printf, or worked around in your own code (which is what I did for Format.jl)

It would be nice to have a complete drop in replacement for Python f-strings (my focus was on equivalent functionality, not equivalent syntax)

**Comment by jariji** [comment]
> Are you planning on supporting the rest of the Python formatting functionality

The other thing that's missing in PyFormattedStrings.jl is Python's `format(x, fmt)` which is needed when you're making the formatter before the `x` is available.

**Comment by ScottPJones** [comment]
I suppose if you really wanted to have the syntax more like Python's (`"formatstring".format(args)`) you could have the macro return a struct, and then define `getproperty` on that type, i.e. something like `py"{abc {x:.2f} {y:d}".format((x=1, y=2.2))`

**Comment by ScottPJones** [comment]
I do need to update the docs (it's no longer a work in progress, it's been stable for a long time now).
I do believe that the syntax in StrFormat is less "fiddly" than the Python f-strings though, and Rust f-strings don't have some of the features (such as formatting with thousand separators [, or _] like Python and this do)

**Comment by ScottPJones** [comment]
> The other thing that's missing in PyFormattedStrings.jl is Python's `format(x, fmt)` which is needed when you're making the formatter before the `x` is available.

That is present in [JuliaString/Format.jl](https://github.com/JuliaString/Format.jl), i.e.
```julia
julia> format("π = {:6.3f}, {:^8.4s}", pi, "🍕")
"π =  3.142,    🍕   "
```
