### ISSUE TITLE
Unlink being a fork of Formatting.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaString/Format.jl#77]
It was discussed on slack that it may be possible to email github support to unlink this repo as a fork of Formatting .jl.

I think it would greatly help users know that this is the original repo where they should file issues and PRs. Typically, when I see a fork, I try to go to the original project and interact there, which is why it would be nice to decouple (and this project diverged many years ago).

**Comment by ScottPJones** [comment]
Unlinked!
